UFL 2024-11-23_23-25-09

diff --git a/bin/scripts/tmux1 b/bin/scripts/tmux1
--- a/bin/scripts/tmux1
+++ b/bin/scripts/tmux1
@@ -1,14 +1,16 @@
 #!/bin/bash
-
+source '/etc/environment'
+source $OSIRIS000_VENV_PATH/bin/activate
 # Variables de entorno configurables
 SESSION_NAME="${SESSION_NAME:-my_tmux_session_$(date +%s)}"
 VIDEO_FILE="${VIDEO_FILE:-${OSIRIS000_BIN}/com/datas/ffmpeg/intro.mp4}"
 ERROR_LOG="${ERROR_LOG:-mpv_errors.log}"
 COMMAND_PANEL0="${COMMAND_PANEL0:-$OSIRIS000_BASEPATH/osiris}"
-COMMAND_PANEL1="${COMMAND_PANEL1:-$OSIRIS000_BIN/scripts/performance.sh}"  # Performance Panel
+COMMAND_PANEL1="${COMMAND_PANEL1:-cd $OSIRIS000_BIN && ./osiris_run}"  # Performance Panel
 COMMAND_PANEL2="${COMMAND_PANEL2:-$OSIRIS000_BIN/pilottv}"
 COMMAND_PANEL3="${COMMAND_PANEL3:-/home/$USER/otvs -screen -prompt}"
-COMMAND_PANEL4="${COMMAND_PANEL4:-$OSIRIS000_BIN/scripts/tails}"
+COMMAND_PANEL4="${COMMAND_PANEL4:-$OSIRIS000_BIN/scripts/progress_tv}"
+COMMAND_PANEL5="${COMMAND_PANEL5:-$OSIRIS000_BIN/scripts/progress_hls}"
 
 # Crear una nueva sesión de tmux con nombre único
 tmux new-session -d -s "$SESSION_NAME" -n window0
@@ -19,30 +21,33 @@ tmux split-window -h -t "$SESSION_NAME:window0" -p 25
 # En el panel derecho (que será el panel 1), dividir en cuatro paneles horizontales
 tmux split-window -v -t "$SESSION_NAME:window0.1" -p 75
 tmux split-window -v -t "$SESSION_NAME:window0.2" -p 66
-tmux split-window -v -t "$SESSION_NAME:window0.3" -p 50
+tmux split-window -v -t "$SESSION_NAME:window0.3" -p 25
+tmux split-window -h -t "$SESSION_NAME:window0.4" -p 50
 
 # Enviar comandos a cada panel de la sesión y ventana específicos
 tmux send-keys -t "$SESSION_NAME:window0.0" "$COMMAND_PANEL0" C-m  # osiris a la izquierda
 tmux send-keys -t "$SESSION_NAME:window0.1" "$COMMAND_PANEL1" C-m  # Performance derecha top
 tmux send-keys -t "$SESSION_NAME:window0.2" "$COMMAND_PANEL2" C-m  # pilottv en la parte 2 derecha
 tmux send-keys -t "$SESSION_NAME:window0.3" "$COMMAND_PANEL3" C-m  # otvs en la parte 3 derecha
-tmux send-keys -t "$SESSION_NAME:window0.4" "$COMMAND_PANEL4" C-m  # mpv en la parte inferior derecha
+tmux send-keys -t "$SESSION_NAME:window0.4" "$COMMAND_PANEL4" C-m  # progress tv en la parte inferior derecha
+tmux send-keys -t "$SESSION_NAME:window0.5" "$COMMAND_PANEL5" C-m  # progress hls en la parte inferior derecha
 
 # Habilitar el uso del ratón para la sesión específica
 tmux set-option -t "$SESSION_NAME" mouse on
 
 # Esperar un momento para que los comandos se ejecuten
-sleep 2
 
 # Verificación de errores en el panel 4 de la sesión específica
-tmux send-keys -t "$SESSION_NAME:window0.4" "wait" C-m
-sleep 2
-tmux capture-pane -t "$SESSION_NAME:window0.4" -pS -1000 | grep -q "Error"
+#tmux send-keys -t "$SESSION_NAME:window0.5" "wait" C-m
+sleep 1
 
-if [ $? -eq 0 ]; then
-  echo "Error al cargar mpv. Verifica el archivo de log: $ERROR_LOG"
-  tmux send-keys -t "$SESSION_NAME:window0.4" "bash" C-m
-fi
+
+#tmux capture-pane -t "$SESSION_NAME:window0.5" -pS -1000 | grep -q "Error"
+
+#if [ $? -eq 0 ]; then
+#  echo "Error al cargar mpv. Verifica el archivo de log: $ERROR_LOG"
+#  tmux send-keys -t "$SESSION_NAME:window0.5" "bash" C-m
+#fi
 
 
 # Adjuntar a la sesión
